language: kotlin
jdk:
  - oraclejdk8

install: echo "skip 'gradle assemble' step"
script:
  - gradle build --continue
  - sonar-scanner

addons:
  sonarcloud:
    organization: "hadrienmp-github"

after_success:
- bash <(curl -s https://codecov.io/bash)
